export * from "./Header"
export * from "./Hero"
export * from "./LoyalCustomer"
export * from "./WhySection"
export * from "./CEO"
export * from "./Feature"
export * from "./JoinUs"
export * from "./Footer"